pipeline {
    // master executor should be set to 0
    agent any
    stages {
    	stage("Start Pull Latest Image"){
    		steps {
    	     	bat "docker pull ahmedhakem/cucumber-docker:cucumber-docker"
    	    }	
    	}
    	stage("Start Grid"){
    	     steps {
    	     	bat "docker-compose up -d hub firefox edge chrome"
    	    }
    	}
    	stage("Run Tests"){
    	     steps {
    	     	bat "docker-compose up testng-module"
    	    }
    	}
    }
    post {
        always {
            step([$class: 'Publisher', reportFilenamePattern: 'testng_results/testng-results.xml'])
            cucumber buildStatus: 'null', customCssFiles: '', customJsFiles: '', failedFeaturesNumber: -1, failedScenariosNumber: -1, failedStepsNumber: -1, jsonReportDirectory: "testng_results", fileIncludePattern: '**/*.json', pendingStepsNumber: -1, skippedStepsNumber: -1, sortingMethod: 'ALPHABETICAL', undefinedStepsNumber: -1
            bat "docker-compose down"
        }
    }
}
